### ISSUE TITLE
Attendee registration/reservation for workshops and special sessions

### ISSUE THREAD

**Issue by jandd** [devdaydresden/devday_website#116]
Some sessions (workshops and excursions) have a limited number of possible attendees. It is necessary to reserve a spot in these sessions before attending.

**Preconditions**

- event is open for attendee registration
- attendee is registered for the event
- session has been accepted by the committee and has a time slot assigned

**Describe the solution you'd like**

- a session should have an optional field that indicates the maximum number of attendees
- a waiting list for the session (1:n relation between session and attendee) needs to be implemented. Entries in the list should have a time stamp and a state (active/pending)
- it should be possible to allow more attendees than free slots (how many?)
- attendees need a way to reserve their spot in the waiting list
- attendees should be able to cancel their reservation from the session detail view and their profile view, cancellation deletes the reservation from the database
- if an early reservation is cancelled the earliest pending reservation is activated and the waiting attendee is notified
- the reservation should be linked from the session detail view
- there should be an overview of the sessions that needs reservation (on the session grid and/or a specialized views
- the system should make sure that attendees cannot reserve spots in two sessions with overlapping time slots
- the reservations should be removed when the event is archived

**Comment by stefanbethke** [comment]
Looks great! I'd add one more point:
* When checking in an attendee, show confirmed session attendee status to the person checking in the attendee, and they can hand out a token or sticker as a "ticket" for that session.

If we figure out a way to print badges, the attendee status could be printed on the badge, of course.

**Comment by ronnyfriedland** [comment]
Maybe its a good idea to send a confirmation to the attendee after successful reservation?

**Comment by jandd** [comment]
progress on this issue can be tracked in https://github.com/jandd/devday_website/tree/limited-session-reservation

**Comment by jandd** [comment]
Fixed by the merge of #147
