### ISSUE TITLE
Add REST Endpoint for Tweetfetching

### ISSUE THREAD

**Issue by artifactdev** [devdaydresden/devday_website#123]
**Is your feature request related to a problem? Please describe.**
The Application should check new tweets with Hashtag '#devdaydd' in a short interval, the fetched tweets should be served via API REST Endpoint to use it in the Twitterwall.

**Describe the solution you'd like**
API Endpoint which serves Tweets like the Twitter API but without restrictions.

**Comment by stefanbethke** [comment]
```
{
 id : number;
 text : string;
 profileImage: string;
 screenName: string;
 location: string;
 time: string;
}
```
