### ISSUE TITLE
Allow attendees to vote on sessions (during event)

### ISSUE THREAD

**Issue by stefanbethke** [devdaydresden/devday_website#124]
**Describe the solution you'd like**
Right after a talk has finished (or maybe a couple minutes before that), let attendees vote on the quality of the talk, and submit a comment. This allows the organizers to give feedback to speakers, and would allow us to present "best talk" at the closing session.

**Comment by stefanbethke** [comment]
In addition:
* Allow all attendees to select in their profile if they want to take part in the final raffle
* Allow attendees to fill in a general feedback form; questions tbd.
* Automatically draw raffle prized from all attendees that have voted on talk or have submitted the general feedback form, and have agreed to take part in the raffle.

**Comment by jandd** [comment]
work on this feature started in https://github.com/jandd/devday_website/tree/attendee_feedback
