### ISSUE TITLE
Session archive view

### ISSUE THREAD

**Issue by stefanbethke** [devdaydresden/devday_website#126]
**Describe the solution you'd like**
Design and implement a list of sessions from past Dev Days that is clearly different from the current event (grid/list).

Easy solution: list and detail views

Maybe folding elements

**Comment by jandd** [comment]
I created this wireframe for the archive list view. The icons on the right should only be visible if the corresponding talk.models.TalkMedia instance exists and has values in the youtube/slideshare/codelink fields.

![wireframe_session_list](https://user-images.githubusercontent.com/249001/53795390-2ef16f00-3f32-11e9-81c1-0332ec7b54e3.png)

**Comment by stefanbethke** [comment]
@artifactdev Can you please provide some HTML structure/CSS styling for the new archive page? The current rough draft can be inspected on the test system.

**Comment by jandd** [comment]
@artifactdev thanks for styling the archive list view in #133. It would be great if the session detail pages for archived sessions would be recognizable as archived somehow too. It's a bit hard to tell that i.e. https://www.devday.de/devday16/talk/keynote-englisch-rationale-continuous-delivery/ is a session from a past year.

**Comment by artifactdev** [comment]
@jandd Like we wrote a PR is comming, needs some rework so the archive class can be set if it's not an actual talk.
