### ISSUE TITLE
Use pre-built Docker images for prod deployment

### ISSUE THREAD

**Issue by stefanbethke** [devdaydresden/devday_website#172]
**Is your feature request related to a problem? Please describe.**
Right now, the prod containers are built on the prod machine as part of the deployment process. 
**Describe the solution you'd like**
Move to having Travis build tagged builds images, push them to Hub, and deploy from there.

**Comment by jandd** [comment]
a base image is built and used by #230. This should be a good base for building the other images. I published the base image manually now but want to integrate it with the Travis build.

**Comment by jandd** [comment]
The current ansible deployment uses the images built by GitHub actions
