### ISSUE TITLE
Easily send tweets when certain things are updated

### ISSUE THREAD

**Issue by stefanbethke** [devdaydresden/devday_website#183]
**Is your feature request related to a problem? Please describe.**
Dev Day participants and others seem to react to tweets informing them about slides being available for a specific talk, or the video having been uploaded.

**Describe the solution you'd like**
When updating a session with a link to the slides, the video, etc., add a button to create a tweet with a link to the talk and what has been added. This should be optional, so that mere maintenance (fixing typos etc.) will not trigger a tweet.

See also #171

**Comment by jandd** [comment]
obsolete, we dropped twitter support
