### ISSUE TITLE
Attendee Registration broken if logged in

### ISSUE THREAD

**Issue by stefanbethke** [devdaydresden/devday_website#20]
**Describe the bug**
Opening /attendee/register, an exception is shown if you're logged in as an editor (potentially other user categories as well).

It appears tests are not covering this part very well.

**Comment by jandd** [comment]
Exception Type:	TypeError
Exception Value:	get_attendee() takes exactly 2 arguments (1 given)

seems to be a broken API call. I'll add a test for that case and fix the issue.

**Comment by stefanbethke** [comment]
When you fix the first one, a second one pops up. That's why I opened this issue, there might be a little bit more work than just a single fix.

**Comment by jandd** [comment]
our test coverage is lacking in other code paths to. Maybe we can add coverage reports to our travis builds (like in https://github.com/coffeestats/coffeestats-django/blob/master/.travis.yml). I'll try to fix the issue and everything I find thereafter and add test while doing that :-)
