### ISSUE TITLE
[API] Mark/unmark session as favorite

### ISSUE THREAD

**Issue by jandd** [devdaydresden/devday_website#225]
PUT .../favourite/<session-slug>
DELETE .../favourite/<session-slug>

**Comment by jenslauterbach** [comment]
@jandd I have started working on this issue. Minor update on your specification:

I'd change

> PUT .../favourite/
> DELETE .../favourite/

to:

```
POST /api/favourite/
DELETE /api/favourite/{pk}
```

**Comment by jandd** [comment]
then it would be `PUT /api/favourite/{id}` and `DELETE /api/favourite/{id}`. I'm not sure whether it is a good idea to expose our internal primary keys/ids. I think we should use the slug-texts that we have for sessions and events and use for other public facing URLs too. Something like `/api/favourite/{event_slug}/{talk_slug}` would be ideal from my point of view. If we go this route we should use such URLs for all API objects.
