### ISSUE TITLE
Implement states for talk submissions

### ISSUE THREAD

**Issue by jandd** [devdaydresden/devday_website#25]
**Is your feature request related to a problem? Please describe.**
Currently speakers can submit talks and can modify the summary and description whenever they like. This can cause problems for reviewers/committee members and the talk presentation after an event.

**Describe the solution you'd like**
I suggest to implement a kind of state machine for talks that has consequences on the actions that are possible to do with the talk. I would like to store the state transitions and their data.

**Actor** | **Action** | **State transition**
-----------|-------------|-------------------------
Speaker | Add | \<new\> → draft
Speaker | Edit | draft → draft
Speaker | Submit for review | draft → submitted
Committee | Comment | submitted → submitted
Committee | Request for changes | submitted → draft 
Committee | Accept | submitted → accepted by committee
Speaker | Confirm | accepted by committee → confirmed by speaker
DevDay team | Add to session grid | confirmed by speaker → published

**Describe alternatives you've considered**

**Additional context**
The implementation of this feature will affect a lot of view and form code and may break things, writing test for all touched views and forms is a must.
The consequences of each state transition needs to be described / implemented
At least the state transitions initiated by the Speaker until the `submitted` state need to be implemented before the call for papers.

**Comment by stefanbethke** [comment]
I'm afraid that speakers will forget to submit their talk; I think just having a single state for draft and submitted will be sufficient.

**Comment by jandd** [comment]
@stefanbethke I think you are right. The committee can still request edits from the speaker if the quality or content is insufficient for judging whether the talk can be accepted or not.

**Comment by stefanbethke** [comment]
Work continues for next year in #125.
