### ISSUE TITLE
Mark archive pages more clearly

### ISSUE THREAD

**Issue by stefanbethke** [devdaydresden/devday_website#28]
**Describe the bug**
The design of the archive pages features the teaser for the upcoming conference clearly, but there's less indication that the program you're looking at is actually for a past event.

**To Reproduce**
https://www.devday.de/devday17/talk/

**Expected behavior**
Either modify the teaser on the archive pages to make it clear it's a teaser for the upcoming event, remove it entirely, or make the actual page title ("Sessionplan 2017") more prominent.

**Comment by stefanbethke** [comment]
This bug is based on this feedback:

> Wobei mich die Struktur der Talk-Seite zunächst einmal ziemlich durcheinander gebracht hatte, ich habe mehrere Sekunden verwirrt auf den Bildschirm gestarrt, bis ich erkannt hatte, dass die Seite, die mir der Browser anzeigt, tatsächlich zu dem Link gehört, auf den ich geklickt hatte, und wo auf der Seite die Informationen stehen, die ich suche. Ich hätte mehr etwas wie in dem angehängten Mockup erwartet.
> 
> Was vielleicht auch nicht optimal ist, ist, dass Talks aus dem Archiv mit dem visuellen Context der nächsten Konferenz angezeigt werden, der oben verlinkte Talk findet mitnichten am 21. Mai 2019 statt.
![talkdetail](https://user-images.githubusercontent.com/3328988/46572567-935ed100-c988-11e8-91f6-6514e11ce281.jpg)

**Comment by fhars** [comment]
There is actually no hint (apart from the fact that the number in the URL is smaller than 95) that you are looking at an archived talk on the actual talk pages, e.g. https://www.devday.de/session/speaker/28/

**Comment by jandd** [comment]
This has been addressed by the new archive and speaker detail pages
