### ISSUE TITLE
Twitterwall not accessible anymore 

### ISSUE THREAD

**Issue by artifactdev** [devdaydresden/devday_website#290]
**Describe the bug**
On a later version of the website it included the twitterwall-app which was accessible under https://devday.de/app-twitterwall/
With this domain we get a 404 from nginx now.

**To Reproduce**
1. Go to https://devday.de/app-twitterwall/

**Expected behavior**
Twitterwall UI should be opened and tweets shown.

**Additional context**
The Twitterwall was updated as well (see PR in devday_twitterwall repo) and should be updated.

**Comment by jandd** [comment]
Twitterwall has been deployed at https://www.devday.de/app-twitterwall/
