### ISSUE TITLE
Update github actions to docker/build-push-action@v3

### ISSUE THREAD

**Issue by jandd** [devdaydresden/devday_website#301]
Our actions currently use https://github.com/docker/build-push-action@v2 which uses some deprecated GitHub actions functionality. We should upgrade the actions to docker/build-push-action@v3.

**Comment by Dyna-Soar** [comment]
I think v3 is backward compatible with your usage. I assume `uses: build-push-action@v2` should simply be replaced by `uses: build-push-action@v2` in main.yml and dev-build.yml
