### ISSUE TITLE
Make rooms unique wrt event

### ISSUE THREAD

**Issue by stefanbethke** [devdaydresden/devday_website#38]
**Describe the bug**
Right now, we only use one set of rooms for all events. Each event needs its own list of rooms.

**To Reproduce**
https://www.devday.de/devday16/talk/

The column Rotterdam should not be there.

**Comment by stefanbethke** [comment]
@jandd this has been fixed with your refactoring, right?

**Comment by jandd** [comment]
Yes it is fixed with #69
