### ISSUE TITLE
We need CMS Module for sponsor area

### ISSUE THREAD

**Issue by artifactdev** [devdaydresden/devday_website#54]
**Is your feature request related to a problem? Please describe.**
We need a specific structure for displaying the sponsors correctly, currently this structure is only possible by editing in html mode. We should find an easier way to add new sponsors.

**Describe the solution you'd like**
A CMS Editor plugin which adds a div with selectable classes, for example we can put an element in the editor and than we can give this element element the numbers of columns for each of the viewports and generell (col-12, col-sm-6, col-lg-3, ..). This element should take linked images as content.

**Describe alternatives you've considered**
We could edit the needed columns in html view of the editor 

**Additional context**
Required codestructur for sponsor area:
`<div class="col-12"> <a href="https://www.t-systems-mms.com/"> <img src="" class="align-center " width="420"> </a></div><div class="col-6 col-md-3"> <a href="https://www.t-systems-mms.com/"> <img src="" width="250"> </a></div><div class="col-6 col-md-3"> <a href="https://www.t-systems-mms.com/"> <img src="" width="250"> </a></div><div class="col-6 col-md-3"> <a href="https://www.t-systems-mms.com/"> <img src="" width="250"> </a></div><div class="col-6 col-md-3"> <a href="https://www.t-systems-mms.com/"> <img src="" width="250"> </a></div>`

**Comment by artifactdev** [comment]
`<img src="" width="250">
    </a>`

**Comment by artifactdev** [comment]
`<div class="col-12">
    <a href="https://www.t-systems-mms.com/">
    <img src="" class="align-center " width="420">
    </a>
</div>
<div class="col-6 col-md-3">
    <a href="https://www.t-systems-mms.com/">
    <img src="" width="250">
    </a>
</div>
<div class="col-6 col-md-3">
    <a href="https://www.t-systems-mms.com/">
    <img src="" width="250">
    </a>
</div>
<div class="col-6 col-md-3">
    <a href="https://www.t-systems-mms.com/">
    <img src="" width="250">
    </a>
</div>
<div class="col-6 col-md-3">
    <a href="https://www.t-systems-mms.com/">
    <img src="" width="250">
    </a>
</div>`

**Comment by jandd** [comment]
The sponsoring area and sponsoring possibility display could be accomplished with the current implementation. Improvements should be requested in separate issues.
