### ISSUE TITLE
Allow attendees to vote on sessions (for session grid)

### ISSUE THREAD

**Issue by stefanbethke** [devdaydresden/devday_website#71]
**Is your feature request related to a problem? Please describe.**
As organizers, we're interested in two metrics: when planning the session grid, how many attendees will likely want to hear a talk, and after the event, how did attendees like each talk.

**Describe the solution you'd like**
After the program committee has selected the talks for the event, attendees should be able to register interest in the talks. The exact format has to be determined; for the organizers, a ranked list of talks needs to be produced, so we can make sure popular talks are not scheduled in the same time slot, and are scheduled in larger rooms.

**Comment by stefanbethke** [comment]
Record which users have cast at least one vote during the event, and use this list of attendees for the final drawing of giveaways.

**Comment by stefanbethke** [comment]
Flag for enabling voting

**Comment by jandd** [comment]
progress can be tracked in https://github.com/jandd/devday_website/tree/attendee-session-voting

**Comment by jandd** [comment]
We need at least a minimal display of aggregated scores for staff members. A CSV export would be a valid alternative.
