### ISSUE TITLE
Attendees should be active only after the user can log in

### ISSUE THREAD

**Issue by stefanbethke** [devdaydresden/devday_website#78]
**Describe the bug**
Right now, we treat the existence of an Attendee object as proof that a user can and will attend the event.

**Expected behavior**
We should ensure that we only consider Attendee objects valid for which the user has completed the double-opt-in activation, and can log in to the site.

**Comment by stefanbethke** [comment]
@jandd is this still an issue?

**Comment by jandd** [comment]
@stefanbethke I'll test it. I think this should be mitigated by the current login/registration flow.

**Comment by jandd** [comment]
People cannot attend if they are not logged in. There is an issue with former attendees who did never activate their email address though. We need to provide a way to get a new activation mail if a user exists but is not marked as active.

**Comment by jandd** [comment]
activation issue will be fixed in #149
